# Default values for stream-data-processor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: trushnesh/home_automation
  tag: 1.0-SNAPSHOT
  imagePullPolicy: Always
  command: [ "echo", "SUCCESS" ]

imagePullSecrets:
- name: regcreds

kafka:
  enabled: true
  bootstrapAddress:

verbose: true

prom:
  enabled: true
